pub const CapabilityDefinition = struct {
    id: []const u8,
    cli_path: []const u8,
    mcp_tool: []const u8,
    summary: []const u8,
    phase: []const u8,
    mutates_state: bool,
    safe_local_validation: bool,
};

pub const all = [_]CapabilityDefinition{
    .{
        .id = "system.os_info",
        .cli_path = "system os-info",
        .mcp_tool = "system_os_info",
        .summary = "Read host OS, version, architecture, and machine name.",
        .phase = "windows-real, linux/mac-basic",
        .mutates_state = false,
        .safe_local_validation = true,
    },
    .{
        .id = "system.cpu_info",
        .cli_path = "system cpu-info",
        .mcp_tool = "system_cpu_info",
        .summary = "Read CPU architecture, logical core count, and page size.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = false,
        .safe_local_validation = true,
    },
    .{
        .id = "system.memory_info",
        .cli_path = "system memory-info",
        .mcp_tool = "system_memory_info",
        .summary = "Read host memory totals, availability, and load percentage.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = false,
        .safe_local_validation = true,
    },
    .{
        .id = "system.disk_list",
        .cli_path = "system disk-list",
        .mcp_tool = "system_disk_list",
        .summary = "Enumerate mounted local disks with free and total bytes.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = false,
        .safe_local_validation = true,
    },
    .{
        .id = "system.process_list",
        .cli_path = "system process-list",
        .mcp_tool = "system_process_list",
        .summary = "Enumerate running processes with pid and executable name.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = false,
        .safe_local_validation = true,
    },
    .{
        .id = "system.hardware_info",
        .cli_path = "system hardware-info",
        .mcp_tool = "system_hardware_info",
        .summary = "Read host hardware profile including cpu, memory, and machine identifiers.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = false,
        .safe_local_validation = true,
    },
    .{
        .id = "system.network_info",
        .cli_path = "system network-info",
        .mcp_tool = "system_network_info",
        .summary = "Enumerate network adapters with ipv4, mac address, and dhcp state.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = false,
        .safe_local_validation = true,
    },
    .{
        .id = "mouse.position",
        .cli_path = "mouse position",
        .mcp_tool = "mouse_position",
        .summary = "Read the current cursor coordinates on the virtual desktop.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = false,
        .safe_local_validation = true,
    },
    .{
        .id = "mouse.move",
        .cli_path = "mouse move --x <x> --y <y> [--duration-ms <ms>] [--jitter-px <px>] [--step-delay-ms <ms>]",
        .mcp_tool = "mouse_move",
        .summary = "Move the cursor with a smooth human-like trajectory, jitter, and delay.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = true,
        .safe_local_validation = false,
    },
    .{
        .id = "mouse.click",
        .cli_path = "mouse click [--button <left|right|middle>] [--count <n>]",
        .mcp_tool = "mouse_click",
        .summary = "Send mouse click events with configurable button and repeat count.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = true,
        .safe_local_validation = false,
    },
    .{
        .id = "mouse.scroll",
        .cli_path = "mouse scroll --delta <amount>",
        .mcp_tool = "mouse_scroll",
        .summary = "Send a wheel scroll delta at the current cursor position.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = true,
        .safe_local_validation = false,
    },
    .{
        .id = "window.list",
        .cli_path = "window list [--include-hidden] [--pid <pid>]",
        .mcp_tool = "window_list",
        .summary = "Enumerate top-level windows with bounds, titles, and optional pid filtering.",
        .phase = "windows-real, linux/mac-basic-unverified",
        .mutates_state = false,
        .safe_local_validation = true,
    },
    .{
        .id = "window.foreground",
        .cli_path = "window foreground",
        .mcp_tool = "window_foreground",
        .summary = "Inspect the current foreground window without mutating focus.",
        .phase = "windows-real, linux/mac-basic-unverified",
        .mutates_state = false,
        .safe_local_validation = true,
    },
    .{
        .id = "window.activate",
        .cli_path = "window activate --handle <handle>",
        .mcp_tool = "window_activate",
        .summary = "Request foreground activation for a specific top-level window handle.",
        .phase = "windows-real, linux/mac-basic-unverified",
        .mutates_state = true,
        .safe_local_validation = false,
    },
    .{
        .id = "window.show",
        .cli_path = "window show --handle <handle>",
        .mcp_tool = "window_show",
        .summary = "Show a window and request foreground activation.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = true,
        .safe_local_validation = false,
    },
    .{
        .id = "window.minimize",
        .cli_path = "window minimize --handle <handle>",
        .mcp_tool = "window_minimize",
        .summary = "Minimize a top-level window by handle.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = true,
        .safe_local_validation = false,
    },
    .{
        .id = "window.maximize",
        .cli_path = "window maximize --handle <handle>",
        .mcp_tool = "window_maximize",
        .summary = "Maximize a top-level window by handle.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = true,
        .safe_local_validation = false,
    },
    .{
        .id = "window.restore",
        .cli_path = "window restore --handle <handle>",
        .mcp_tool = "window_restore",
        .summary = "Restore a minimized or maximized window by handle.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = true,
        .safe_local_validation = false,
    },
    .{
        .id = "window.move",
        .cli_path = "window move --handle <handle> --x <x> --y <y> [--width <n>] [--height <n>]",
        .mcp_tool = "window_move",
        .summary = "Move a window to target coordinates and optionally resize it.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = true,
        .safe_local_validation = false,
    },
    .{
        .id = "window.find",
        .cli_path = "window find --title <text>",
        .mcp_tool = "window_find",
        .summary = "Find one window by title match with optional pid and visibility filters.",
        .phase = "windows-real, linux/mac-basic",
        .mutates_state = false,
        .safe_local_validation = true,
    },
    .{
        .id = "window.close",
        .cli_path = "window close --handle <handle>",
        .mcp_tool = "window_close",
        .summary = "Request graceful close for a top-level window using native close message.",
        .phase = "windows-real, linux-real, mac-stub",
        .mutates_state = true,
        .safe_local_validation = false,
    },
    .{
        .id = "app.launch",
        .cli_path = "app launch --target <path-or-uri>",
        .mcp_tool = "app_launch",
        .summary = "Launch an app, document, or URI using host shell integration.",
        .phase = "windows-real, linux/mac-real",
        .mutates_state = true,
        .safe_local_validation = false,
    },
    .{
        .id = "clipboard.get_text",
        .cli_path = "clipboard get-text",
        .mcp_tool = "clipboard_get_text",
        .summary = "Read clipboard text using the platform clipboard API.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = false,
        .safe_local_validation = true,
    },
    .{
        .id = "clipboard.set_text",
        .cli_path = "clipboard set-text --text <value>",
        .mcp_tool = "clipboard_set_text",
        .summary = "Write clipboard text. Local validation must restore the prior value.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = true,
        .safe_local_validation = false,
    },
    .{
        .id = "clipboard.get_files",
        .cli_path = "clipboard get-files",
        .mcp_tool = "clipboard_get_files",
        .summary = "Read clipboard file-drop paths from the shell clipboard format.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = false,
        .safe_local_validation = true,
    },
    .{
        .id = "clipboard.set_files",
        .cli_path = "clipboard set-files --paths <path1;path2;...>",
        .mcp_tool = "clipboard_set_files",
        .summary = "Write clipboard file-drop payload so paste can deliver files into target apps.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = true,
        .safe_local_validation = false,
    },
    .{
        .id = "clipboard.set_image",
        .cli_path = "clipboard set-image --path <image-file>",
        .mcp_tool = "clipboard_set_image",
        .summary = "Load one image file into clipboard bitmap content for direct image paste.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = true,
        .safe_local_validation = false,
    },
    .{
        .id = "keyboard.key_press",
        .cli_path = "keyboard key --key <name>",
        .mcp_tool = "keyboard_key_press",
        .summary = "Send a single virtual-key press and release.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = true,
        .safe_local_validation = false,
    },
    .{
        .id = "keyboard.hotkey",
        .cli_path = "keyboard hotkey --keys <combo>",
        .mcp_tool = "keyboard_hotkey",
        .summary = "Send a key combination such as ctrl+shift+s.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = true,
        .safe_local_validation = false,
    },
    .{
        .id = "keyboard.type_text",
        .cli_path = "keyboard type --text <value>",
        .mcp_tool = "keyboard_type_text",
        .summary = "Send Unicode text input using synthetic keyboard events.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = true,
        .safe_local_validation = false,
    },
    .{
        .id = "keyboard.type_keys",
        .cli_path = "keyboard type-keys --text <value> [--key-delay-ms <ms>]",
        .mcp_tool = "keyboard_type_keys",
        .summary = "Type by keyboard layout key positions like human key presses, not direct Unicode injection.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = true,
        .safe_local_validation = false,
    },
    .{
        .id = "keyboard.ime_switch",
        .cli_path = "keyboard ime-switch [--strategy <win-space|alt-shift|ctrl-shift>]",
        .mcp_tool = "keyboard_ime_switch",
        .summary = "Switch active input method using configured OS shortcut strategy.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = true,
        .safe_local_validation = false,
    },
    .{
        .id = "keyboard.caps_lock",
        .cli_path = "keyboard caps-lock [--state <toggle|on|off>]",
        .mcp_tool = "keyboard_caps_lock",
        .summary = "Toggle or enforce caps lock state for uppercase/lowercase control.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = true,
        .safe_local_validation = false,
    },
    .{
        .id = "keyboard.paste",
        .cli_path = "keyboard paste",
        .mcp_tool = "keyboard_paste",
        .summary = "Send Ctrl+V to the active window. Guarded local validation only.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = true,
        .safe_local_validation = false,
    },
    .{
        .id = "screen.capture",
        .cli_path = "screen capture [--path <file>] [--display-id <id>] [--window-handle <handle>]",
        .mcp_tool = "screen_capture",
        .summary = "Capture all displays by default, or target one display/window when specified.",
        .phase = "windows-real, linux/mac-basic-unverified",
        .mutates_state = false,
        .safe_local_validation = true,
    },
    .{
        .id = "screen.pixel_color",
        .cli_path = "screen pixel-color --x <x> --y <y>",
        .mcp_tool = "screen_pixel_color",
        .summary = "Read RGB color for one screen pixel on the virtual desktop.",
        .phase = "windows-real, linux/mac-basic-unverified",
        .mutates_state = false,
        .safe_local_validation = true,
    },
    .{
        .id = "screen.displays",
        .cli_path = "screen displays",
        .mcp_tool = "screen_displays",
        .summary = "Enumerate displays with primary flag and bounds.",
        .phase = "windows-real, linux/mac-basic-unverified",
        .mutates_state = false,
        .safe_local_validation = true,
    },
    .{
        .id = "wait.window",
        .cli_path = "wait window --title <text>",
        .mcp_tool = "wait_window",
        .summary = "Poll for a matching window title with timeout and foreground filters.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = false,
        .safe_local_validation = true,
    },
    .{
        .id = "wait.focus",
        .cli_path = "wait focus --title <text>",
        .mcp_tool = "wait_focus",
        .summary = "Poll the foreground window until its title matches the requested text.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = false,
        .safe_local_validation = true,
    },
    .{
        .id = "wait.activate",
        .cli_path = "wait activate --handle <handle> [--expect-active <true|false>] [--timeout-ms <ms>]",
        .mcp_tool = "wait_activate",
        .summary = "Poll whether a target window handle becomes active or inactive in foreground.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = false,
        .safe_local_validation = true,
    },
    .{
        .id = "wait.pixel",
        .cli_path = "wait pixel --x <x> --y <y> --hex <RRGGBB>",
        .mcp_tool = "wait_pixel",
        .summary = "Poll one screen pixel until its color matches the requested RGB hex value.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = false,
        .safe_local_validation = true,
    },
    .{
        .id = "wait.clipboard",
        .cli_path = "wait clipboard [--expect-text <value>]",
        .mcp_tool = "wait_clipboard",
        .summary = "Poll clipboard text until it changes or matches an expected text condition.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = false,
        .safe_local_validation = true,
    },
    .{
        .id = "wait.process",
        .cli_path = "wait process [--name <text>|--pid <pid>]",
        .mcp_tool = "wait_process",
        .summary = "Poll process list for a target process state transition.",
        .phase = "windows-real, linux/mac-stub",
        .mutates_state = false,
        .safe_local_validation = true,
    },
};
